### ISSUE TITLE
Use HKPS as default protocol for SKS keyservers

### ISSUE THREAD

**Issue by Diagoras** [s4u/pgpverify-maven-plugin#10]
Currently, the plugin uses the SKS keyserver pool as the default keyserver (good) but requests and receives the keys in plaintext (not as good). It would be nice if the default was HKPS instead, and if HKPS was handled with the same kind of custom scheme and port logic as HKP in the PGPKeysCache constructor in order to support other HKPS keyservers.

However, this would involve grabbing the CA certificate from https://sks-keyservers.net/sks-keyservers.netCA.pem in order to validate the SKS HKPS connections, which especially in Java is a huge pain.

**Comment by slawekjaranowski** [comment]
Resolved by #13
