### ISSUE TITLE
Add hkps://keyserver.ubuntu.com to default key servers

### ISSUE THREAD

**Issue by slawekjaranowski** [s4u/pgpverify-maven-plugin#122]
**Is your feature request related to a problem? Please describe.**
Some of pgp public keys are only deployed to https://keyserver.ubuntu.com/

**Describe the solution you'd like**
Extending default key server list will cause possibility to verification more artifacts.
Also ubuntu seems more stable than https://hkps.pool.sks-keyservers.net/

**Comment by philihp** [comment]
Would recommend hkps://keys.openpgp.org/; as of 2019, it's the default for Enigmal, GPG Tools, etc.

**Comment by slawekjaranowski** [comment]
Thanks for your proposition.
I will try to discover which key servers are preferred for "maven" world.

**Comment by cobratbq** [comment]
I used `hkps://keys.openpgp.org` in https://github.com/cobratbq/keysmap for a trial run. I find that there are many keys missing. So unless this is the result of connection issues, this might not be the most reliable keyserver available for our purpose.
