### ISSUE TITLE
verifyPluginDependencies should enable verifyPlugins

### ISSUE THREAD

**Issue by slawekjaranowski** [s4u/pgpverify-maven-plugin#128]
When we set option `verifyPluginDependencies` to `true` but not configure `verifyPlugins` also to `true` the first option don't have any effect.

Settings `verifyPluginDependencies`  to true should force `verifyPlugins` also will be enabled without any additional configuration.

**Comment by cobratbq** [comment]
I agree. The (only?) other option I see is to simply emit a warning or even an error and make clear that the configuration does not make sense. However, if the user already decided to validate plugin dependencies, it should be reasonable to assume that the plugins themselves are relevant too.
