### ISSUE TITLE
deprecates strictNoSignature

### ISSUE THREAD

**Issue by slawekjaranowski** [s4u/pgpverify-maven-plugin#129]
If `keysMap` is present should contains all needed information.

Actually we have more options for keys in `keysMap` as `noSig`, `noKey`.

**Comment by cobratbq** [comment]
So, the following compositions are relevant:

1. `failNoSignature` without keysmap: always fail if artifact is not signed.
1. `failNoSignature` with keysmap: always fail if artifact is not signed.
1. no `failNoSignature` without keysmap: allow unsigned artifacts.
1. no `failNoSignature` with keysmap: only allow if present in keysmap with `noSig`.

`failNoSignature` makes sense as long as it gets priority over the keysmap. Indeed, `strictNoSignature` is no longer necessary as we can express the same inside the keysmap.

**Comment by slawekjaranowski** [comment]
As you see when we add next parameter - matrix of possible situation will grow very quickly.

So I'm thinking how and when reduce duplicate options. And make configuration more clear.

Maybe better solution is to prohibit to use `failNoSignature=true` when keysMap is defined.

**Comment by cobratbq** [comment]
> As you see when we add next parameter - matrix of possible situation will grow very quickly.

Yes, indeed.

> So I'm thinking how and when reduce duplicate options. And make configuration more clear.

Yes, agree.

> Maybe better solution is to prohibit to use `failNoSignature=true` when keysMap is defined.

Well, `failNoSignature` when using a keysmap can still be valuable. Scenario: I want to enforce that only verifyable dependencies are used, while using a keysmap from github.com/s4u/pgp-keys-map. Even if the keysmap contains `noSig` entries, they are still not allowed because of `failNoSignature`.
