### ISSUE TITLE
Special case for matching version 0.0.0.M5

### ISSUE THREAD

**Issue by slawekjaranowski** [s4u/pgpverify-maven-plugin#135]
**Describe the bug**

When we define items in keysMap many artifacts don't have version  - so all version should be accepted.
Artifacts with version like 0.0.0-qualifier are not meet this requirement. 

**To Reproduce**

Add to keyMaps
    
    org.eclipse.sisu:org.eclipse.sisu.inject = 0xCF17E92C9FFA55316B5DB83901D734EE5EE9C3F8

next add dependency:

    <dependency>
      <groupId>org.eclipse.sisu</groupId>
      <artifactId>org.eclipse.sisu.inject</artifactId>
      <version>0.0.0.M5</version>
  </dependency>

**Expected behavior**

When no version are present in KeyMaps all version should be accepted.

**Additional context**

By default for all version matching we use pattern `[0.0.0,)` for maven VersionRange.

But version with any qualifera are older than version without qualifier,eg. `1.0-alpha-1` < `1.0`
https://cwiki.apache.org/confluence/display/MAVENOLD/Versioning

So in our case is true `0.0.0.M5` < `0.0.0` and version `0.0.0.M5` is not range ....

**Comment by cobratbq** [comment]
Is it possible to match on unspecified versions, e.g. `[,)` or `*` wildcard or something like that? It seems like you basically want to match everything.

**Comment by slawekjaranowski** [comment]
unfortunately - `[,)` is not valid range
I prepared some fix, where don't use version range for matching all version.
