### ISSUE TITLE
Plugin should fail when new versions of a dependency are unsigned

### ISSUE THREAD

**Issue by Diagoras** [s4u/pgpverify-maven-plugin#16]
If a signed dependency is updated to a new, unsigned version the plugin should fail the build with an appropriate error message since this is very sketchy behaviour. This involves keeping track of a mapping of groupId + artifactId to keys, something which is already partially implemented with the "keyMap".

**Comment by Kortanul** [comment]
@Diagoras doesn't this already happen?

- if new version is unsigned, there is no `.asc` file to pull down for the artifact.
- if new version re-uses the `.asc` file from the original version, the signature won't match.

can you elaborate?

**Comment by Diagoras** [comment]
IIRC, if the new version is unsigned you're right in that there's no .asc file to pull down. The plugin will not fail, though, and will just ignore the unsigned version. Generally, any signed artifacts should stay signed for all future versions - I'm not sure why anyone would just stop signing releases.

Been a while since I opened this ticket, though, so I might be wrong or this issue might be out of date.

**Comment by Kortanul** [comment]
I believe the option to fail on missing signature takes care of this use case.

**Comment by Diagoras** [comment]
@Kortanul You're right. But if you have some dependencies that are unsigned, you might not have the option to fail on missing signatures. That means dependencies that transition from signed to unsigned will also succeed.

FWIW, this can probably be fix by adding the option for a specific list of unsigned dependencies. That lets you specify the few troublesome dependencies you expect to be unsigned, but ensures the plugin breaks if anything you expect to be signed suddenly changes. That make sense?
