### ISSUE TITLE
Cleanup issues reported by sonar

### ISSUE THREAD

**Issue by slawekjaranowski** [s4u/pgpverify-maven-plugin#179]
**Describe the bug**
Sonarcloud.io reports some issues in project, please consult report:
https://sonarcloud.io/project/issues?id=org.simplify4u.plugins%3Apgpverify-maven-plugin&resolved=false

**Expected behavior**
No issues is sonarcloud.io, but one less is also appreciate.

**Comment by singloon** [comment]
Hi @slawekjaranowski can you assign this issue to me?
