### ISSUE TITLE
feature request - inherit proxy from Maven

### ISSUE THREAD

**Issue by Kortanul** [s4u/pgpverify-maven-plugin#24]
our project is open-source and public, so we host the trusted keys map on our public HTTPS server. unfortunately, for users behind a firewall who are building our projects, they can't build with PGP verification enabled because the mojo cannot resolve the hostname.

the cause appears to be that pgpverify does not use Maven's configured proxy settings when fetching the keys map from a remote server.

I'm not sure if there's a built-in HTTP client that pgpverify could be using, or if a pattern like `selectProxy()` from `nexus-maven-plugins` is necessary:
https://github.com/sonatype/nexus-maven-plugins/blob/master/common/src/main/java/org/sonatype/maven/mojo/settings/MavenSettings.java

**Comment by slawekjaranowski** [comment]
Some workaround was described in: #1

**Comment by slawekjaranowski** [comment]
IMHO better will be use maven wagon library

**Comment by Kortanul** [comment]
thanks, @slawekjaranowski. I've been looking into using the wagon as well, but we'll give the workaround a try as well.

**Comment by slawekjaranowski** [comment]
Using wagon will be some difficult, I'm looking for another way.

In project I use plexus ResourceManager which don't use wagon and don't support proxy configurations from maven settings.

**Comment by cobratbq** [comment]
IIUC, this is only an issue when retrieving PGP keys from a keyserver, as that is where pgpverify establishes a connection by itself. Has someone looked into whether simply applying the active proxy settings from Maven to the HttpClient is an option? It seems reasonable and should tackle at least some of the use cases, though maybe not the `NTLM` authentication requirement use case. (Which can be worked around in other ways if necessary.)
