### ISSUE TITLE
pgpverify:check doesn't honor mvn --offline option

### ISSUE THREAD

**Issue by sewe** [s4u/pgpverify-maven-plugin#245]
As of version 1.11.0, the `pgpverify:check` goal always contacts remote keyservers, even if Maven is invoked with the `--offline` command line option.

IMHO, the goal should simply skip updating its cache and possibly print out a `INFO`-level message that it did so.

**Comment by slawekjaranowski** [comment]
What should be in offline mode done if key doesn't exist in local cache?

**Comment by slawekjaranowski** [comment]
I mark it as a bug ... maven offline mode should be respected by design.

**Comment by sewe** [comment]
> What should be in offline mode done if key doesn't exist in local cache?

I would simply fail the build with an error, similar to when Maven needs to download a dependency that is not yet cached in the local repository.

**Comment by joschi** [comment]
> I would simply fail the build with an error, similar to when Maven needs to download a dependency that is not yet cached in the local repository.

I agree, but then it should be possible to fetch all the required signatures with a separate goal, similar to [`dependency:go-offline`](https://maven.apache.org/plugins/maven-dependency-plugin/go-offline-mojo.html).

**Comment by slawekjaranowski** [comment]
for `go-offline `feature please create new issue.
