### ISSUE TITLE
Allow multiple KeysMap files to be specified

### ISSUE THREAD

**Issue by sewe** [s4u/pgpverify-maven-plugin#246]
At the moment, the `pgpverify:check` goal allows only a single [`<keysMapLocation>`](https://www.simplify4u.org/pgpverify-maven-plugin/check-mojo.html#keysMapLocation) to be given.

The primary use case would be combining a public KeysMap file like [`pgp-keys-map`](https://github.com/s4u/pgp-keys-map) with a private one, which specifies the mappings for artifacts not on Maven Central, possibly signed with keys not on a public keyserver (think company Nexus + company PGP keyserver).

This could be implemented in a backward compatible way, if `<keysMapLocation>` becomes a [“inlined collection” parameter](https://blog.sonatype.com/2011/03/configuring-plugin-goals-in-maven-3/) with an `addKeysMapLocation` method in the mojo; even when the mojo uses a list of locations internally, the user would simply be able to use multipe `<keysMapLocation>` elements directly below `<configuration>` without a wrapper element like `<keysMapLocation>`:

```xml
<configuration>
  <keysMapLocation>/pgp-keys-map.list</keysMapLocation>
  <keysMapLocation>company-keys-map.list</keysMapLocation>
</configuration>
```

Merging multiple KeysMap files would be done in the straight‐forward way, with latter (property‐like) KeysMap files overwriting the properties of the former.

**Comment by sewe** [comment]
> To discover - how data from many files for the same item should be merged?

Maybe just merging the key/maps, like I initially suggested is too simplistic.

**Two couple of use cases that are worth thinking about:**

1. Should a later KeysMap file be able to add a more specific rule as an exception, e.g., to override a rule that was too coarse grained?
   ```
   # First KeysMap file
   test.groupId = 0x1234567890123456789012345678901234567890
   ```
   ```
   # Second KeysMap file
   test.groupId:artifactId = 0xABCDEF0123456789ABCDEF0123456789ABCDEF01
   ```

2. But how would one then be able to override exceptions granted in the former KeysMap file, in order to enforce stricter rules?
   ```
   # First KeysMap file
   test.groupId = 0x1234567890123456789012345678901234567890
   test.groupId:artifactId = badSig
   ```
   ```
   # Second KeysMap file
   test.groupId:artifactId = 0x1234567890123456789012345678901234567890 # Ignore the badSig. Cumbersome. :-(
   ```

Maybe thinking in terms of merging key/value data-structures is the wrong level of abstraction. Instead, it might be more fruitful to think about the _verdicts_ reached according to the rules in each KeysMaps file and how these verdicts are combined. Essentially, each KeysMap file can result in one of three verdicts:

1. The fact that the given Maven coordinate is signed by the given PGP key ID satisfy the rules in this KeysMap file.
2. The fact that the given Maven coordinate is signed by the given PGP key ID violate the rules in this KeysMap file.
3. This KeysMap file has no rules that apply to the given Maven coordinate.

So, for a Maven coordinate like ` test.groupId:artifactId:jar:1.0` signed by PGP key ID `0xABCDEF0123456789ABCDEF0123456789ABCDEF01`, _Use Case 1_ above would reach verdicts of "This violates the rules of the first KeysMap file" and "This satisfies the rules of the second KeysMap file".

Now the question is whether a later verdict should override the former or whether we want to employ a (stricter) policy of "The rules of at least one KeysMap file must be satisfied _and_ the rules of no KeysMap file must be _violated_".

**Comment by pavelhoral** [comment]
> To discover - how data from many files for the same item should be merged?

I would argue that it should behave in a same way like all the entries comes from a single file (i.e. no merging, just "append" the values). My understanding was that you can enter the same key multiple times... isn't that the case?

```
foo:bar=0x1234
foo:bar=0x4567
foo:bar=0x89..
```

Btw. my use-case for this feature would be to have a shared library project with its own keymap file such that I don't have to define trusted keys of transitive depenencies.

**Comment by sewe** [comment]
> My understanding was that you can enter the same key multiple times... isn't that the case?

Good point. Maybe I was led astray by this sentence from [the documentation](https://www.simplify4u.org/pgpverify-maven-plugin/keysmap-format.html): “The format of the file is similar to, but more flexible than, a Java properties file.” But unlike Java properties files, which are really just key/value maps and where keys have to be unique, KeysMap files _might  be_ more like list of rules: “The order of items is not important, all matching items are checked for keys or special values. Process is continued until first matching item is found or end of items is reached.”

I say “might be,” however, as if find the above confusing; how can the order of items not be important when the process continues _until_ the first match.

Perhaps I simply don’t understand the KeysMap file format well enough yet to make a recommendation. :disappointed:

**Comment by slawekjaranowski** [comment]
Probably for one file I assume that all items are independent.

By the way, when I read it, I see now that sentence is inconsistent, when process stop on first found item - order is important.

So first we refactor behavior for one keys map ...

**Comment by slawekjaranowski** [comment]
I prepared a test for loading multiple keys map, please look.

**Comment by slawekjaranowski** [comment]
another idea - support include and exclude for `keysMap`, configuration item can look like as
```xml
<keysMap>
    <location>/keys-map.list</location>
    <include>tast.group:test-artifatc...</include>
    <include>...</include>
    <exclude>tast.group = noSig</exclude>
    <exclude>...</exclude>
</keysMap>
```
item from `keysMap` will be added if any `include` will match and all `exclude` does't match

**Comment by slawekjaranowski** [comment]
and issue with inline connection of plugin configuration which I found: 
https://issues.apache.org/jira/browse/MNG-7133

**Comment by slawekjaranowski** [comment]
Code is ready, I will merge it in next two days ... and at weekend I will release next version.
