### ISSUE TITLE
Option to treat noSig/badSig/noKey special values from KeysMapFile as failures

### ISSUE THREAD

**Issue by sewe** [s4u/pgpverify-maven-plugin#247]
Using a public KeysMap file rather than rolling your own is very appealing. However, it may contain exceptions that one is not comfortable with, allowing some files to have no signature or an invalid signature via the `noSig`, `badSig` and `noKey` [special values](https://www.simplify4u.org/pgpverify-maven-plugin/keysmap-format.html#PGP_keys_special_values).

It would hence be nice to have an option to override this lenient behavior, i.e., to use the KeysMap file but treat `noSig`, `badSig` or `noKey` (as configured) as failures.

AFAICT, [`<failNoSignature>`](https://www.simplify4u.org/pgpverify-maven-plugin/check-mojo.html#failNoSignature) already does this for `noSig`, so maybe all that is needed are matching `<failBadSignature>` and `<failNoKey>` configuration options.

(Note that this feature request is not about prohibiting the use of `noSig`, `badSig` or `noKey` in a KeysMap file, as that would prevent one from re-using existing files; it is about overriding the associated lenient behavior.)

**Comment by slawekjaranowski** [comment]
Idea to discuss ... 
I think that we should connect this with #246

**Comment by slawekjaranowski** [comment]
`<failNoSignature>` is used in first stage - when artifacts and signature is resolved it is not connected with data in `keysMap` file.

I would prefer to deprecate / remove this option and take all decisions based on `keysMap` 

There is request for feature of possibility to declare multiple `keysMap` I think that we can add some of exclude / include mechanizm to `keysMap`, so we can load `keysMap` without eg `noSig` special value and if we want we can prepare next `keysMap` when we allow `noSig` for special artifacts only.

**Comment by slawekjaranowski** [comment]
We will have `include/exclude` possibility on `kysMap` files, I hope that such option will be more flexible.
