### ISSUE TITLE
Goal for downloading PGP keys and signatures

### ISSUE THREAD

**Issue by joschi** [s4u/pgpverify-maven-plugin#248]
Similar to the [`dependency:go-offline`](https://maven.apache.org/plugins/maven-dependency-plugin/go-offline-mojo.html) goal for downloading all dependencies of a Maven project, there should be a goal for downloading the signatures and the corresponding PGP keys for all dependencies of a Maven project in order to allow working offline with a project.

While this can be achieved with building the complete Maven project, this involves some overhead (compiling source files, etc.) which could be avoided with a dedicated goal for this purpose.

Refs https://github.com/s4u/pgpverify-maven-plugin/issues/245

**Comment by slawekjaranowski** [comment]
What with: #130 in this context.
