### ISSUE TITLE
Skipping Verification for a specific library

### ISSUE THREAD

**Issue by DukeDavis12** [s4u/pgpverify-maven-plugin#306]
**Is your feature request related to a problem? Please describe.**
I am getting `Execution default of goal org.simplify4u.plugins:pgpverify-maven-plugin:1.14.0:check failed: Failed to process signature for artifact org.json:json:pom:20201115` error. So there should be a way to manual skip the verification of such libraries. I couldn't find anything related to skipping a specific library from verification in your documentation.

**Describe the solution you'd like**
- Ability to skip a library.
- Adding documentation for the same.

**Describe alternatives you've considered**

**Additional context**

**Comment by slawekjaranowski** [comment]
root cause is missing public key on key servers

```
mvn org.simplify4u.plugins:pgpverify-maven-plugin:show -Dartifact=org.json:json:20201115

[ERROR] All servers from list was failed
[INFO] 

Artifact:
	groupId:     org.json
	artifactId:  json
	type:        jar
	version:     20201115

PGP signature:
	version:     4
	algorithm:   SHA1withRSA
	keyId:       0x83D7DB7C18913CA4
	create date: Sun Nov 15 22:01:38 CET 2020
	status:      invalid


PGP server returned an error: HTTP/1.1 404 Not Found for: https://pgp.mit.edu/pks/lookup?op=get&options=mr&search=0x83D7DB7C18913CA4
```

you can use `keysMap` - https://www.simplify4u.org/pgpverify-maven-plugin/check-mojo.html#keysMapLocation
with content:

```
org.json:json:20201115 = noKey
```
in order to pass verification

**Comment by DukeDavis12** [comment]
Thanks for the response
________________________________

**Comment by slawekjaranowski** [comment]
https://github.com/stleary/JSON-java/issues/612

**Comment by slawekjaranowski** [comment]
put on hold for waiting until JSON-Java to publish your public key.
