### ISSUE TITLE
pgp validation of poms done against local poms ?

### ISSUE THREAD

**Issue by javabeanz** [s4u/pgpverify-maven-plugin#31]
due to differences in lineendings, poms might be different on the local fille system than in the Maven repo. I think the pgp validation should be done against the pom from the Maven repo because now they might fail for the wrong reason.

**Comment by slawekjaranowski** [comment]
Can you give some example, how to reproduce it?
Which operating system, maven version.

**Comment by slawekjaranowski** [comment]
if still occurs, please reopen
