### ISSUE TITLE
Pattern-based version matching, specifically for SNAPSHOT-only keys

### ISSUE THREAD

**Issue by ao-apps** [s4u/pgpverify-maven-plugin#344]
We would like the ability to specify keys map entries only for *-SNAPSHOT versions.  This is so our Jenkins may sign snapshots, while releases (not done by Jenkins) will not accept the Jenkins GPG signing key.

We have tried `groupId:*:*-SNAPSHOT`, but that does not appear to work.

Is there a way to do this?

Are you willing to allow this feature?  If so, we'll be happy to look into implementing it.

If we do implement it, would a regular expression implementation be preferred over glob, perhaps with "~" prefix?
`groupId:*:~.*-SNAPSHOT$`

**Comment by slawekjaranowski** [comment]
Please implement.

**Comment by ao-apps** [comment]
We have implemented with ~ prefix to indicate regular expression: #346

**Comment by ao-apps** [comment]
@slawekjaranowski Thank you for the [recent release of pgp-keys-map](https://github.com/s4u/pgp-keys-map/releases/tag/v2021.12.28).  We hope you will find it in your new-year schedule to release the latest [pgpverify-maven-plugin](https://github.com/s4u/pgpverify-maven-plugin/), too.
