### ISSUE TITLE
How to automatically generate the depends page on the website?

### ISSUE THREAD

**Issue by zhanglc** [s4u/pgpverify-maven-plugin#397]
Hi, 

Thanks for your great works , it helps a lot .

 I have a question:

 is this page https://www.simplify4u.org/pgpverify-maven-plugin/dependencies.html automatically generated? 
 
 if Yes,  could u show me how to do it ? 

thanks very much.

**Comment by 123Haynes** [comment]
@zhanglc in the sites sourcecode it says

>Generated by Apache Maven Doxia Site Renderer 1.9.2 from org.apache.maven.plugins:maven-project-info-reports-plugin:3.1.2:dependencies at 2022-01-05
 | Rendered using Apache Maven Fluido Skin 1.9

That should be a good starting point :)

**Comment by slawekjaranowski** [comment]
Apache Maven Project Info Reports Plugin generate such reports
https://maven.apache.org/plugins/maven-project-info-reports-plugin/index.html
https://maven.apache.org/plugins/maven-project-info-reports-plugin/dependencies-mojo.html

Project Info Reports Plugin is used by Maven site
https://maven.apache.org/guides/mini/guide-site.html

**Comment by zhanglc** [comment]
@123Haynes @slawekjaranowski thanks a lot. 

I will try them.
