### ISSUE TITLE
fresh checkedout build fails

### ISSUE THREAD

**Issue by javabeanz** [s4u/pgpverify-maven-plugin#41]
mvn install gives :

ERROR] The build could not read 1 project -> [Help 1]
[ERROR]   
[ERROR]   The project org.simplify4u.plugins:pgpverify-maven-plugin:1.4.0-SNAPSHOT (/home/blabla/projects/pgpverify-maven-plugin/pom.xml) has 1 error
[ERROR]     Non-resolvable parent POM for org.simplify4u.plugins:pgpverify-maven-plugin:1.4.0-SNAPSHOT: Could not find artifact org.simplify4u:parent:pom:2.4.0-SNAPSHOT and 'parent.relativePath' points at no local POM @ line 20, column 13 -> [Help 2]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 

using jdk 11.01 on centos 7 and maven 3.10

**Comment by slawekjaranowski** [comment]
Please update to the latest version from master.
I released new version of parent pom.

**Comment by javabeanz** [comment]
build completes now, but with many errors and warnings, during test phase. Maybe use Travis or some other build service ?

**Comment by slawekjaranowski** [comment]
I use travis:
https://travis-ci.org/s4u/pgpverify-maven-plugin

**Comment by javabeanz** [comment]
yes, and in the travis build logs for jdk 1.8 i see : 
[INFO] [INFO] BUILD FAILURE

Somehow some errors are ignored, maybe it's only tests, but it can made a bit better, right ?

**Comment by slawekjaranowski** [comment]
Some error logs was from integration tests which expect error.
Now we don't logs from test - so build log is more clean.
