### ISSUE TITLE
Possible security issue while retreiving/using PGP keys

### ISSUE THREAD

**Issue by martinm1000** [s4u/pgpverify-maven-plugin#42]
I've looked at the code and **I think** I see a problem, which could prevent this plugin to do its job (ie.: warning that a pined certificate for an artefact changed). Also note that I might have missed something looking at the code and this issue might not be a problem after all. I didn't test this.

#### Problem
Please see the two links at the end to read about suck attacks. But to resume, someone can publish a key that clone text fields of an existing key and compute to the same KeyId. 

Such keys have been found before on key servers. Note that if an attacker is on the network level, retrieving a key could produce only 1 result, with the cloned key. If key is pined by the developer using its KeyId I think the plugin will fail to detect this.

- KeyId are collision prone (and existing attacks are doing just that, by 'cloning' complete keys).
- KeyId seems to be used internally as a key in the Map<> tracking certificates.

#### Possible solution
- Do not use KeyId but certificate Fingerprints everywhere possible, which are more unique (but still could have collisions with other keys. But better odds than with KeyId)
- Handle the situation when retreiving a Key returns more than 1 certificate
- Force the 'pining' of a certificate for an artefact to only use the full fingerprint
- Have a unit test for this (cloned certificate, same KeyId as original, new version of artefact signed with cloned key)

### References
https://lkml.org/lkml/2016/8/15/445
https://searchsecurity.techtarget.com/answer/How-can-PGP-short-key-IDs-be-protected-from-collision-attacks

**Comment by slawekjaranowski** [comment]
I've looked something for this topic.

So when we start proces of verification we only have signature for file and from signature we get keyId for public kay.

And next in OpenPGP Message Format - RFC4880 whe have eight-octet keyId  - 5.2.  Signature Packet (Tag 2)

So we can only use long keyId (64 bits) and this value is used for searchnig key.

For mapping key to artifact we can use fingerprint of public key.

**Comment by slawekjaranowski** [comment]
There is IssuerFingerprint in RFC4880bis - #86
