### ISSUE TITLE
Make pgpverify-maven-plugin thread-safe

### ISSUE THREAD

**Issue by joschi** [s4u/pgpverify-maven-plugin#43]
When trying to build a multi-module project with multiple threads, Maven will emit the following warning:
```
# mvn -T 3 install
[...]
[WARNING] *****************************************************************
[WARNING] * Your build is requesting parallel execution, but project      *
[WARNING] * contains the following plugin(s) that have goals not marked   *
[WARNING] * as @threadSafe to support parallel building.                  *
[WARNING] * While this /may/ work fine, please look for plugin updates    *
[WARNING] * and/or request plugins be made thread-safe.                   *
[WARNING] * If reporting an issue, report it against the plugin in        *
[WARNING] * question, not against maven-core                              *
[WARNING] *****************************************************************
```

While the build usually continues, I also encountered occasional NullPointerExceptions in pgpverify-maven-plugin.

**Comment by slawekjaranowski** [comment]
Thank you for your issue.
Can you provided some stack trace with NullPointerException?
Does NullPointerException occurs only in multi thread execution?

**Comment by joschi** [comment]
> Can you provided some stack trace with NullPointerException?
Unfortunately I can't for now. The CI workspace is gone and the NPEs weren't logged on stdout.

I also cannot reproduce the issue consistently.

> Does NullPointerException occurs only in multi thread execution?

At least it's the only time I've ever seen them.

**Comment by slawekjaranowski** [comment]
Current implementation of key retrieval is not thread safe. 

It may occurs that two separate thread try to download and save the same key and in result file with key may contains invalid data.

**Comment by cobratbq** [comment]
If the issue is only about key retrieval, it may make sense to simply serialize this. That is, assume that key retrieval is relatively rare, i.e. only needed for first run. All other runs would operate from local key cache. Hence keeping it simple and enabling support for multi-threading.
