### ISSUE TITLE
Rafactor of artifacts resolving

### ISSUE THREAD

**Issue by slawekjaranowski** [s4u/pgpverify-maven-plugin#45]
Deprecated ProjectDependenciesResolver - should be replaced by something newer.

All job with resolving, filtering artifacts should be moved to dedicated class in order to minimize code lines of mojo class.

New implementation should be ready for resolving project plugins dependency - #5

**Comment by cobratbq** [comment]
I'm currently looking into this. No promises yet. (https://github.com/cobratbq/pgpverify-maven-plugin/tree/rewrite-artifact-resolution)
