### ISSUE TITLE
Inconsistent reporting of "successful" artifact verification with `strictNoSignature` and empty keys map

### ISSUE THREAD

**Issue by cobratbq** [s4u/pgpverify-maven-plugin#51]
When running `pgpverify:check` with an empty keys map, i.e. keys map is configured but refers to an empty file, _signed artifacts_ are verified by valid signature only - ignoring keys map - while `strictNoSignature` fails _unsigned artifacts_ for missing entry in keys map.

Personally, I would argue that if configuration parameter `keysMapLocation` is present, then it should fail artifact signature verificatoin even if the keys map is empty. However, strictly speaking this is backwards-incompatible for a very peculiar edge case.

**Comment by cobratbq** [comment]
@slawekjaranowski would you be okay with treating an empty keys-map as "invalidate all artifacts as none are included in the keys-map"?

**Comment by slawekjaranowski** [comment]
connect with: #129

**Comment by slawekjaranowski** [comment]
strictNoSignature is deprecated - so we can close this
