### ISSUE TITLE
warning during artifact signature download

### ISSUE THREAD

**Issue by slawekjaranowski** [s4u/pgpverify-maven-plugin#53]
In logs we can see:

    [WARNING] Could not validate integrity of download from
      https://repo.maven.apache.org/maven2/org/apache/maven/plugins/maven-ejb-plugin/3.0.1/maven-ejb-plugin-3.0.1.jar.asc:
      Checksum validation failed, no checksums available

We should discover how to download asc files in proper way

**Comment by cobratbq** [comment]
Ah right, so when we download the `.asc` files, maven automatically assumes there is an `md5` or `sha1` "partner"-file and that does not exist.

**Comment by slawekjaranowski** [comment]
I asked about it on https://lists.apache.org/list.html?dev@maven.apache.org

**Comment by cobratbq** [comment]
The recent change (4ff359cdfd9917af04cb984dd6b62df9be5bd868) fixes the problem for me.

**Comment by laeubi** [comment]
Even though there is a workaround now, I have created https://issues.apache.org/jira/browse/MNG-7560 to get a more standard way to do such tasks, maybe someone likes to leave a comment or even suggest a PR :-)
