### ISSUE TITLE
Need help - Report missing

### ISSUE THREAD

**Issue by LS-IEM** [s4u/pgpverify-maven-plugin#550]
Hi,
cannot find report when running plugin goal check as scribed in https://www.simplify4u.org/pgpverify-maven-plugin/report-format.html 

Is there a trick or special settings?

**Comment by slawekjaranowski** [comment]
You need a set param `reportWrite` to `true`
https://www.simplify4u.org/pgpverify-maven-plugin/check-mojo.html#reportWrite

**Comment by LS-IEM** [comment]
Thanks! Rtfm….

Mit freundlichen Grüßen

Stefan Leuthner
Softwareentwickler

[IEM_Claim]

Fon:     +49 241 41259-426
Mail:     ***@***.******@***.***>
Web:    www.iem.de<http://www.iem.de/>

IEM GmbH - Headquarter
Gewerbepark Brand 42 | 52078 Aachen | Germany
Fon: +49 241 41259-300 | Fax: +49 241 41259-311

IEM GmbH – Service & Logistics
(bitte ausschließlich für alle Warensendungen nutzen / kindly return equipment and units for repair to this address)
Im Erdbeerfeld 20 | Halle C, EG | 52078 Aachen | Germany

Website<https://www.iem.de/> | facebook<https://www.facebook.com/IEM.GmbH/> | Twitter<https://twitter.com/IEMGmbH> | XING<https://www.xing.com/companies/iemgmbh> | LinkedIn<https://www.linkedin.com/company/iemgmbh/> | Youtube<https://www.youtube.com/channel/UCy1bNr9yQUA564bqrQ_zXLA> | Disclaimer<https://www.iem.de/e-mail-disclaimer/>


Von: Slawomir Jaranowski ***@***.***>
Datum: Dienstag, 28. Mai 2024 um 09:30
An: s4u/pgpverify-maven-plugin ***@***.***>
Cc: Leuthner, Stefan ***@***.***>, Author ***@***.***>
Betreff: Re: [s4u/pgpverify-maven-plugin] Need help - Report missing (Issue #550)

You need a set param reportWrite to true
https://www.simplify4u.org/pgpverify-maven-plugin/check-mojo.html#reportWrite
