### ISSUE TITLE
Validate transitive closure of dependencies of build plug-ins and atypical dependencies

### ISSUE THREAD

**Issue by cobratbq** [s4u/pgpverify-maven-plugin#59]
Both dependencies of build plug-ins and dependencies that are referenced in atypical locations, such as maven-compiler-plugin annotation processors, are not fully validated. We currently only validate the explicitly referenced dependency itself, but not its transitive closure of dependencies (and their corresponding version after conflict resolution).

Includes indirect dependencies of #54. (Direct dependencies of build plug-ins are already validated.)

Question asked at: https://lists.apache.org/thread.html/e58b66152de1c388e55fb9e86f7d1fefe357a80d5b2f33ab0aef48da%40%3Cdev.maven.apache.org%3E

**Comment by slawekjaranowski** [comment]
```mvn dependency:go-offline ``` - probably does what we want

example output:
```
[INFO] >>> maven-dependency-plugin:2.8:go-offline (default-cli) > :resolve-plugins @ pgpverify-maven-plugin >>>
[INFO] 
[INFO] --- maven-dependency-plugin:2.8:resolve-plugins (resolve-plugins) @ pgpverify-maven-plugin ---
[INFO] Plugin Resolved: sitemapxml-maven-plugin-2.0.0.jar
[INFO]     Plugin Dependency Resolved: maven-core-3.5.0.jar
[INFO]     Plugin Dependency Resolved: maven-plugin-api-3.5.0.jar
[INFO]     Plugin Dependency Resolved: junit-4.12.jar
[INFO] Plugin Resolved: maven-jar-plugin-3.2.0.jar
[INFO]     Plugin Dependency Resolved: maven-plugin-api-3.0.jar
[INFO]     Plugin Dependency Resolved: maven-core-3.0.jar
[INFO]     Plugin Dependency Resolved: maven-artifact-3.0.jar
[INFO]     Plugin Dependency Resolved: file-management-3.0.0.jar
[INFO]     Plugin Dependency Resolved: maven-archiver-3.5.0.jar
[INFO]     Plugin Dependency Resolved: maven-shared-utils-3.2.1.jar
[INFO]     Plugin Dependency Resolved: plexus-archiver-4.2.1.jar
[INFO]     Plugin Dependency Resolved: plexus-utils-3.3.0.jar
...
```

**Comment by cobratbq** [comment]
That's interesting. The intention for this build goal comes as close as possible to what I'm looking for. That is, it doesn't simply look at the artifact and its requirements, but rather at the reactor, because otherwise you would still not be able to use it off-line. This seems sufficiently reliable/trustworthy as a starting point. I'll have a look at it soon.

**Comment by cobratbq** [comment]
`maven-dependency-plugin` goal `go-offline` does seem to offer a solution. I need to look further into if there's going to be licensing issues when adopting the logic from `maven-dependency-plugin` (more or less) literally.
Issue #77 becomes more critical once this functionality is available, as we will be validating _significantly_ more artifact.

**Comment by slawekjaranowski** [comment]
Interesting code can be in some apache shared library, so maybe it is enough use it

https://maven.apache.org/plugins/maven-dependency-plugin/dependencies.html

**Comment by cobratbq** [comment]
> Interesting code can be in some apache shared library, so maybe it is enough use it

This is resolved by using other resolution logic. I missed a very obvious solution to the transitive closure resolution problem. That is, there is a flag to indicate transitive resolution. I was too prejudiced to look at the obvious place :-/

The remaining issue is deviation in signing practices:
- POM files may be unsigned while dependencies/plugins themselves are signed.
- POM files may be signed while dependencies/plugins are unsigned.
- POM files may be signed with different public key than dependencies/plugins.

Progress so far at https://github.com/cobratbq/pgpverify-maven-plugin/tree/validate-indirect-dependencies

**Comment by cobratbq** [comment]
> The remaining issue is deviation in signing practices:
> [...]

This is now solved with a built-in exception in case a POM-artifact can be checked to have different signature acceptance criteria than the plugin/dependency artifact. This is a workaround, however relatively small, so it seems acceptable to me to include it for the benefit of all supported cases.

_NOTE_ the last remaining issue under investigation: the artifacts `struts-core`, `struts-taglib` and `struts-tiles` have bad signatures. (That is, `gpg` cannot do successful validation.)

**Comment by slawekjaranowski** [comment]
Which plugins use struts 1.3.8?
as I see work on remove dependency on struts is in progress
https://issues.apache.org/jira/browse/DOXIASITETOOLS-215

Good work - thanks again.

Could you create (even draft) PR it will be easier to review early.

**Comment by slawekjaranowski** [comment]
I was looking more bit, and found:
`org.apache.maven.plugin.internal.PluginDependenciesResolver` which is implement by `org.apache.maven.plugin.internal.DefaultPluginDependenciesResolver`

I found it by running:

    MAVEN_OPTS="-Dorg.slf4j.simpleLogger.showLogName=true" mvn clean package -X 

example output:
```
[DEBUG] org.eclipse.aether.internal.impl.collect.DefaultDependencyCollector - Dependency collection stats: {ConflictMarker.analyzeTime=226592, ConflictMarker.markTime=104230, ConflictMarker.nodeCount=237, ConflictIdSorter.graphTime=93941, ConflictIdSorter.topsortTime=43250, ConflictIdSorter.conflictIdCount=81, ConflictIdSorter.conflictIdCycleCount=0, ConflictResolver.totalTime=1496713, ConflictResolver.conflictItemCount=188, DefaultDependencyCollector.collectTime=114397529, DefaultDependencyCollector.transformTime=2033190}
[DEBUG] org.apache.maven.plugin.internal.DefaultPluginDependenciesResolver - org.apache.maven.plugins:maven-javadoc-plugin:jar:3.1.1
[DEBUG] org.apache.maven.plugin.internal.DefaultPluginDependenciesResolver -    org.apache.maven:maven-core:jar:3.0:compile
[DEBUG] org.apache.maven.plugin.internal.DefaultPluginDependenciesResolver -       org.apache.maven:maven-settings-builder:jar:3.0:compile
[DEBUG] org.apache.maven.plugin.internal.DefaultPluginDependenciesResolver -       org.apache.maven:maven-repository-metadata:jar:3.0:compile
[DEBUG] org.apache.maven.plugin.internal.DefaultPluginDependenciesResolver -       org.apache.maven:maven-model-builder:jar:3.0:compile
[DEBUG] org.apache.maven.plugin.internal.DefaultPluginDependenciesResolver -       org.apache.maven:maven-aether-provider:jar:3.0:runtime
[DEBUG] org.apache.maven.plugin.internal.DefaultPluginDependenciesResolver -       org.sonatype.aether:aether-impl:jar:1.7:compile
[DEBUG] org.apache.maven.plugin.internal.DefaultPluginDependenciesResolver -          org.sonatype.aether:aether-spi:jar:1.7:compile
[DEBUG] org.apache.maven.plugin.internal.DefaultPluginDependenciesResolver -       org.sonatype.aether:aether-api:jar:1.7:compile
[DEBUG] org.apache.maven.plugin.internal.DefaultPluginDependenciesResolver -       org.sonatype.aether:aether-util:jar:1.7:compile
[DEBUG] org.apache.maven.plugin.internal.DefaultPluginDependenciesResolver -       org.sonatype.sisu:sisu-inject-plexus:jar:1.4.2:compile
[DEBUG] org.apache.maven.plugin.internal.DefaultPluginDependenciesResolver -          org.sonatype.sisu:sisu-inject-bean:jar:1.4.2:compile
[DEBUG] org.apache.maven.plugin.internal.DefaultPluginDependenciesResolver -             org.sonatype.sisu:sisu-guice:jar:noaop:2.1.7:compile
```

**Comment by slawekjaranowski** [comment]
I start to think, that plugin dependency resolving is some another that for standard artifact.

Each plugin has own classloader where can be put different version of the same artifact.

We should get dependency tree for each plugin, next try to find unique list of artifacts grouped by group, id and version, in order to omit duplicate items for check.

I think we also should remember of source for artifact, so we can display this information if some thing wrong.

**Comment by cobratbq** [comment]
> I start to think, that plugin dependency resolving is some another that for standard artifact.
> Each plugin has own classloader where can be put different version of the same artifact.
> We should get dependency tree for each plugin, next try to find unique list of artifacts grouped by group, id and version, in order to omit duplicate items for check.

Yes, indeed. That is what I was referring to when stating the TODO in the PR:

> check if we should construct the transitive closure based on all collected artifacts together, or all individually, or combination of build plug-in with its dependencies. (resolving too many artifacts in single request may result in too much converged resolved versions.)

I suspected as much. If I would need to design it myself, I would've done a classloader per plugin + its dependencies. And it seems that you've confirmed my suspicions, so thank you :-)

> I think we also should remember of source for artifact, so we can display this information if some thing wrong.

I agree.

**Comment by slawekjaranowski** [comment]
Ok, today I have plan release next version - we have many changes.
This is next big change, i think we can work on it before next release.

**Comment by cobratbq** [comment]
> Ok, today I have plan release next version - we have many changes.
> This is next big change, i think we can work on it before next release.

Sure, no sense in rushing things in or delaying for a long time.

**Comment by slawekjaranowski** [comment]
Done in #80
