### ISSUE TITLE
keymap file must exist in all subprojects

### ISSUE THREAD

**Issue by alexanderkjall** [s4u/pgpverify-maven-plugin#6]
If you specify the plugin in the top level pom file, then all subprojects must have a copy of the file also or the build fails.

**Comment by slawekjaranowski** [comment]
It is standard maven issue - how to share resource between multi module projects, I will not resolve this.

You can look into example for checkstyle configuration: https://maven.apache.org/plugins/maven-checkstyle-plugin/examples/multi-module-config.html

**Comment by alexanderkjall** [comment]
That link was informative thank you, it shows that I'm not that experienced with maven :)
