### ISSUE TITLE
How are keys verified?

### ISSUE THREAD

**Issue by JensErat** [s4u/pgpverify-maven-plugin#9]
How are the OpenPGP keys verified?

Verifying signatures against unverified keys is of very limited use. Skimming the code and looking at the usage examples, I do not see how keys are verified, instead they seem to be fetched automatically based on what key the artifact claims to be issued by (thus, a faked artifact might well just reference a faked key, and thus has a valid signature).

I did not completely read and try to understand the code, but I didn't find any hint keys are verified.

In case this is not available yet, I'd see two possibilities to perform validation of keys:

- Let the developer using the artifacts decide on what keys are allowed, by providing a whitelist of allowed keys (key fingerprints) per artifact.

  The developer could use GnuPG to construct trust paths to the respective keys, if he's using OpenPGP to this extend, he'll have all data in his GnuPG keychain, anyway.

  I guess this is the more reasonabel way.
- Build your own OpenPGP web of trust validation system similar to the one GnuPG uses. Seems a rather complicated thing and not worth the effort, and interfacing GnuPG would probably be more reasonable (and would also not require existing GnuGP users to replicate trust data into the artifact).

**Comment by slawekjaranowski** [comment]
Hi,

You can use keysMap to build whitelist of allowe keys per artifact.
Please look example in integration test:
https://github.com/s4u/pgpverify-maven-plugin/tree/master/src/it/sigOkKeysMap

You can also read description of plugin parameters:
http://www.simplify4u.org/pgpverify-maven-plugin/check-mojo.html

**Comment by JensErat** [comment]
Looking at that, the whitelist proposal is already implemented and looks totally fine. I guess this would be important to include on the homepage, as it's a very relevant part of the plugin.

**Comment by slawekjaranowski** [comment]
Thanks for your suggestion, I will try to add something about this feature to homepage. 
If you would like to add some example or description how to use this plugin, I would be grateful.  
I hope that keysmap options is ok for you now.

Another thing is integration maven plugin with GnuPG keychain.
I think this can be next useful feature.

Maven plugin use bouncycastle library for PGP operations, currently I don't know if BC support GnuPG keychains. If someone has such experience I invite to collaborations.

**Comment by JensErat** [comment]
Yes, the whitelist is totally fine in my opinion -- thank you for providing an important part missing for Maven (given it works, didn't try it yet ;) )...

I'm not sure whether replicating the full web of trust verification is a good thing to do:

- BouncyCastle cannot interface GnuPG
- If people really define trust to be able to use the web of trust, they've got all information in their key chain
- If a key changes and is not trusted yet, the problem is obvious and easy to resolve
- It might actually be easier manually checking the key sometimes; especially since a bunch of keys used for Maven isn't even connected to the web of trust
- The whitelist approach allows sharing the whitelist among collaborators, without everybody having to maintain their own OpenPGP keys
- Finally: it's just a horrible amount of work to do. ;)
