### ISSUE TITLE
Do not expire downloaded signatures (.asc) files

### ISSUE THREAD

**Issue by cobratbq** [s4u/pgpverify-maven-plugin#98]
**Is your feature request related to a problem? Please describe.**
For multiple executions of pgpverify that are sufficiently far apart, signature files of dependencies (`.asc` files) keep getting redownloaded. This is unnecessary (overhead and dependence on internet) as the signatures are not expected to change anyways.

**Describe the solution you'd like**
Download the signature files once. Then keep them in the local repository and reuse them every time. That is, assuming that the signature file itself is downloaded successfully, i.e. not broken/empty/etc.

**Describe alternatives you've considered**
None. I can imagine it is possible to keep them in a separate location or something but that would just mean extra work/risk of failures, etc.

**Comment by slawekjaranowski** [comment]
Signatures (`.asc`) for artifacts are downloaded / resolved by maven resolver and like other artifacts are cached in local repository.

**Comment by slawekjaranowski** [comment]
How do you discovered that `.asc` files aren't cached?

**Comment by cobratbq** [comment]
> How do you discovered that `.asc` files aren't cached?

They are cached. However, while working on #80 for a few days in a row, I noticed that the `.asc` files keep getting redownloaded. Basically I ran `mvn pgpverify:check` twice - on different days - without changing anything, but still a lot of small downloads were performed the second time. I haven't investigated in detail, but figured that there may be some (configurable?) expiration time as the same does not happen for jar-artifacts.

**Comment by slawekjaranowski** [comment]
I have answer:
For failed artifacts downloads maven create `.lastUpdated` file with last error date and some other internal information.

When we want resolve the same artifact again this information is used to immediately return result without try next download.

There is option 'updatePolicy' in maven settings which is responsible for how long this result is valid - default daily - https://maven.apache.org/settings.html

So if project has dependency to non existing `.asc` files maven resolver try find it only once per day - and display message 'Downloading from ...' in first time only.

**Comment by cobratbq** [comment]
ah, so all resolution downloads are all the package for which signatures do not exist. That makes a lot of sense, actually.
